### ISSUE TITLE
OS detect does not work on Amazon Linux 2

### ISSUE THREAD

**Issue by someword** [inspec/train#345]
### Description

Running an EC2 instance based on Amazon Linux 2 I would expect the OS to be identified as a linux redhat/centos variant.

### Train and Platform Version
Train version 1.4.35 (bundled with inspec)
/etc/os-release from host

>NAME="Amazon Linux"
VERSION="2 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

### Replication Case
Create ec2 instance using amazon linux 2 ami.   Install inspec which bundles train 
`sudo yum install -y  https://packages.chef.io/files/stable/inspec/2.2.70/el/7/inspec-2.2.70-1.el7.x86_64.rpm`

Run `inspec detect` to exercise the train os detection code

### Possible Solutions
Changing this line https://github.com/inspec/train/blob/master/lib/train/platforms/detect/helpers/os_linux.rb#L13
to read

` when /Amazon Linux/i
 `

### Stacktrace
From `inspec detect`
`/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/helpers/os_linux.rb:21:in `redhatish_version': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/specifications/os.rb:194:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:46:in `instance_eval'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:46:in `block in scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:60:in `scan_family_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:51:in `block in scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:60:in `scan_family_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:51:in `block in scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:60:in `scan_family_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:51:in `block in scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:45:in `scan_children'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:33:in `block in scan'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:27:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect/scanner.rb:27:in `scan'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/platforms/detect.rb:9:in `scan'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/plugins/base_connection.rb:102:in `platform'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/local.rb:46:in `select_runner'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/local.rb:27:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/local.rb:17:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/train-1.4.35/lib/train/transports/local.rb:17:in `connection'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/backend.rb:51:in `create'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/runner.rb:66:in `configure_transport'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/runner.rb:58:in `initialize'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/cli.rb:277:in `new'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/cli.rb:277:in `run_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/lib/inspec/cli.rb:187:in `detect'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.70/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:103:in `load'
        from /usr/bin/inspec:103:in `<main>'
`

**Comment by chris-rock** [comment]
@someword Thank you for your feedback, I quickly tested the detection with the latest amazonlinux:2 docker container by using InSpec 2.2.70 with Train 1.4.35:

```
inspec detect -t docker://43403dbff9eb

== Platform Details

Name:      amazon
Families:  redhat, linux, unix, os
Release:   2
Arch:      x86_64
```

and it worked without any issues. The code for the detection is located here: https://github.com/inspec/train/blob/master/lib/train/platforms/detect/specifications/os.rb#L189-L196 and in your case it reads `/etc/redhat-release` and `/etc/system-release`. Can you paste the content of those files?

**Comment by someword** [comment]
@chris-rock 

`[ec2-user@ip-10-52-29-143 ~]$ cat /etc/system-release
Amazon Linux release 2 (2017.12) LTS Release Candidate
`
My instances do not have a redhat-release file?
`[ec2-user@ip-10-52-29-143 ~]$ ls /etc/*release*
/etc/os-release  /etc/system-release  /etc/system-release-cpe
`
I ran the docker image you referenced and do not see it has a /etc/redhat-release file either

`❯ docker run -it  amazonlinux:2 ls /etc/redhat-release
ls: cannot access /etc/redhat-release: No such file or directory
`

The /etc/os-release in the docker image is also different than what is in the /etc/os-release file in the ami image.     Let me spin up a raw ec2 amazonlinux 2 instance that does not use any of my companies customizations and make sure I get the same behavior as I originally reported.   We only install a few rpms/systemd units so I didn't think we would have messed with the detection but i'll double check.

**Comment by someword** [comment]
@chris-rock so amazon linux 2 long term support AMI has a different /etc/os-release file as seen here
`[ec2-user@ip-10-52-25-70 ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
`
So i guess the real issue is how can we get amazon LTS images to be seen as amazon linux?  Right now the detection fails.

**Comment by someword** [comment]
For my personal situation it looks like the newest EKS optimized AMI (based on amazon linux 2) has the /etc/os-release format that train is expecting.   It does seem like detecting amazon linux off of the `ID_LIKE="centos rhel fedora"` parameter might be more flexible and still work when they change the format of the /etc/os-release file.

My apologies for misunderstanding the issue when i opened the ticket.
Closing.

**Comment by chris-rock** [comment]
I am not sure I understand how this fixed your initial issue. If I got your report right, there are some cases where train‘s detection is not correct. I think we should fix that and support to detect LTS versions

**Comment by someword** [comment]
@chris-rock  i guess it did not really fix my initial issue.  I just moved to a different ami that train can detect properly.   It looks like in all the amazon linux /etc/os-release the `ID_LIKE="centos rhel fedora"'` entry has been pretty reliable to identify the OS as a redhat variant.   Would that be an option to use that instead of relying on the `NAME` or `PRETTY_NAME`?

**Comment by radhus** [comment]
I started getting this issue on newer Amazon Linux 2 AMIs. I have used the latest 2.2 InSpec docker images for a while and now they don't work out of a sudden. Also tried upgrading to 3.0 but still the same issue.

```
/usr/local/bundle/gems/train-1.5.6/lib/train/platforms/detect/helpers/os_linux.rb:16:in `redhatish_version': undefined method `[]' for nil:NilClass (NoMethodError)
```

@chris-rock is it OK to reopen this?

**Comment by chris-rock** [comment]
@radhus probably related to https://github.com/inspec/train/pull/380

**Comment by tas50** [comment]
@chris-rock You might want to consider making this same change in train: https://github.com/chef/ohai/issues/1298

We're going to continue to run into OS detection issues due to small changes in the text strings of these releases. If we switch to detection via /etc/os-release those issues vanish and we get simpler detection of new / obscure distros.

**Comment by akshit-modi** [comment]
Same issue is faced in newer image of amazon linux 2023. 
```
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
```
